### ISSUE TITLE
poetry dependency version specifications

### ISSUE THREAD

**Issue by ap--** [imi-bigpicture/opentile#21]
Hi @erikogabrielsson 

Great work on `opentile` 🎉 
I wanted try it out just now and noticed you're using poetry caret version requirements to limit the major version of dependencies.
This causes issues for calendar versioned dependencies like tifffile and imagecodecs:

```
tifffile<2022.0.0,>=2021.6.14 
imagecodecs<2022.0.0,>=2021.8.26
```

Where it's basically unpredictable anyways when a breaking change is introduced and currently the newest version is blocked off. It might also block off newer versions of dependencies that undergo a major version increase without breaking the part of the API that opentile uses.

Do you think it would make sense to just limit the minimum required version and run all tests in the CI regularly to detect and deal with incompatibilities with updated dependencies on a case by case basis?

If yes, I can work on a PR.

Cheers,
Andreas 😃

**Comment by erikogabrielsson** [comment]
Thanks for the feedback and suggestion Andreas. Please go ahead with the PR!
