### ISSUE TITLE
test images 

### ISSUE THREAD

**Issue by ap--** [imi-bigpicture/opentile#24]
Hello everyone,

Is it possible to share the test images?
Or are they available somewhere online?

All the best,
Andreas

**Comment by erikogabrielsson** [comment]
Hi,
The tests are currently using non-public slides as test data. I have made a PR changing to openslide public slides for svs and ndpi. Will have to find a philips tiff-slide that we can use.

**Comment by ap--** [comment]
Thanks @erikogabrielsson 

I'll rebase my changes on top of that.
Maybe we could start collecting interesting public test images on a public bucket somewhere, for CI testing.

Cheers,
Andreas 😃

**Comment by erikogabrielsson** [comment]
Thanks for making this PR Andreas. Yes, having more public images would be good. The cytomine collection is a good start (includes openslide test images and more) https://cytomine.com/collection
